name: token

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use secret
        run: echo "My secret is ${{ secrets.NEW_GITHUB_TOKEN }}"
        env:
          MY_SECRET: ${{ secrets.NEW_GITHUB_TOKEN }}
